INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rush Cartoons", "Music", 2000, "2016-04-04", "2016-04-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Led Zeppelin Cartoon", "Music", 2000, "2016-05-04", "2016-05-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Beatles Cartoons", "Music", 2000, "2016-06-04", "2016-06-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Red Hot Chili Peppers Cartons", "Music", 2000, "2016-06-04", "2016-06-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Journey Cartoons", "Music", 2000, "2016-07-04", "2016-07-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Walk the Moon Cartoons", "Music", 2000, "2016-08-04", "2016-08-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Police Cartoons", "Music", 2000, "2016-09-04", "2016-09-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Michael Jackson Cartoons", "Music", 2000, "2016-10-04", "2016-10-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Yes Cartoons", "Music", 2000, "2016-11-04", "2016-11-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Lady Gaga Cartoons", "Music", 2000, "2016-12-04", "2016-12-20");

INSERT INTO users (name, age) VALUES ("Jonathan Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jacob Blanche", 21);
INSERT INTO users (name, age) VALUES ("Justine Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jeremy Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jeffrey Blanche", 21);
INSERT INTO users (name, age) VALUES ("John Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jackson Blanche", 21);
INSERT INTO users (name, age) VALUES ("Julia Blanche", 21);
INSERT INTO users (name, age) VALUES ("Julian Blanche", 21);
INSERT INTO users (name, age) VALUES ("Julianne Blanche", 21);
INSERT INTO users (name, age) VALUES ("Julienne Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jennifer Blanche", 21);
INSERT INTO users (name, age) VALUES ("Justin Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jack Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jordan Blanche", 21);
INSERT INTO users (name, age) VALUES ("James Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jorge Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jim Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jill Blanche", 21);
INSERT INTO users (name, age) VALUES ("Jessica Blanche", 21);

INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (320, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 6, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (22, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (22, 8, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 15, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 14, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 10, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 11, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 18, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 20, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 6, 4);
